version: "3.8"
services:
  weather-forecast-api-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:4000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
