version: '3.8'
services:
  weather-forecast-api-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6000:4000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    command: sh -c "npm run migrate && npm start"
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=weather_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  pgdata:
